module.exports = {
    Chart: require('./Chart'),
    Dialog: require('./Dialog'),
    DragManager: require('./DragManager'),
    Dropdown: require('./Dropdown'),
    DropIndicator: require('./DropIndicator'),
    DropTarget: require('./DropTarget'),
    DropTargetVertical: require('./DropTargetVertical'),
    FilterPanel: require('./FilterPanel'),
    Grid: require('./Grid'),
    PivotButton: require('./PivotButton'),
    PivotCell: require('./PivotCell'),
    PivotChart: require('./PivotChart'),
    PivotRow: require('./PivotRow'),
    PivotTable: require ('./PivotTable'),
    PivotTableColumnButtons: require('./PivotTable.ColumnButtons'),
    PivotTableColumnHeaders: require('./PivotTable.ColumnHeaders'),
    PivotTableDataCells: require('./PivotTable.DataCells'),
    PivotTablePivotTable: require('./PivotTable'),
    PivotTableRowButtons: require('./PivotTable.RowButtons'),
    PivotTableRowHeaders: require('./PivotTable.RowHeaders'),
    PivotTableSizingManager: require('./PivotTable.SizingManager'),
    PivotTableUpperButtons: require('./PivotTable.UpperButtons'),
    VerticalScrollBar: require('./VerticalScrollBar'),
    HorizontalScrollBar: require('./HorizontalScrollBar'),
    Toolbar: require('./Toolbar')
};